export const GET_ALL_POST = 'HOME/GET_ALL_POST';
export const SET_ALL_POST = 'HOME/SET_ALL_POST';
export const FILTER_POST = 'HOME/FILTER_POST';
export const CREATE_POST = 'HOME/CREATE_POST';
export const SET_NEW_POST = 'HOME/SET_NEW_POST';
export const CREATE_NEW_USER = 'HOME/CREATE_NEW_USER';
export const SET_LOADING = 'HOME/SET_LOADING';
export const SET_COUNT = 'HOME/SET_COUNT';