export const USER_LOGIN = 'APP/USER_LOGIN';
export const USER_REGISTER = 'APP/USER_REGISTER';
export const USER_LOGOUT = 'APP/USER_LOGOUT';
export const SET_USER = 'APP/SET_USER';
export const SET_LOADING = 'APP/SET_LOADING';
export const CHANGE_USER_BOOKMARKS = 'APP/CHANGE_USER_BOOKMARKS';
export const SET_ERROR_MESSAGE = 'APP/SET_ERROR_MESSAGE';